### ISSUE TITLE
Improve repo organization and match book text repo

### ISSUE THREAD

**Issue by SuzGupta** [kodecocodes/booh-materials#1]
As per @jellodiil : "tidy your worksheets in the materials repo into chapter folders as well"

**Comment by SuzGupta** [comment]
We definitely don't want to do this for this edition, since we are linking using the current, flat repo structure.

**Comment by jellodiil** [comment]
@SuzGupta 
Sorry, I somehow missed this.

This should really be done for the first edition to bring it inline with all of our materials repos, and since it is just a quick find and replace, I will sort it in my publication pass

**Comment by SuzGupta** [comment]
Thanks! As long as the links in each chapter (at the end of the Action Plan section in a note-style block) also get updated, as we discussed via Discord, this sounds terrific.
